#!/bin/sh

# Safely preview or prune local ProbeWatch deployment archives.
# Usage: prune-archives.sh [--apply] [--keep N] DIRECTORY

set -eu

APPLY=0
KEEP=5
while [ $# -gt 0 ]; do
    case "$1" in
        --apply) APPLY=1; shift ;;
        --keep)
            [ $# -ge 2 ] || { echo "--keep requires a number" >&2; exit 2; }
            KEEP="$2"; shift 2 ;;
        --help|-h)
            printf '%s\n' "Usage: $0 [--apply] [--keep N] DIRECTORY"
            exit 0 ;;
        *) break ;;
    esac
done

[ $# -eq 1 ] || { echo "an explicit archive directory is required" >&2; exit 2; }
ARCHIVE_DIR=$1
case "$ARCHIVE_DIR" in
    ''|/) echo "refusing empty or root archive directory" >&2; exit 2 ;;
esac
[ -d "$ARCHIVE_DIR" ] || { echo "archive directory does not exist: $ARCHIVE_DIR" >&2; exit 2; }
case "$KEEP" in
    ''|*[!0-9]*) echo "--keep must be a non-negative integer" >&2; exit 2 ;;
esac

ARCHIVE_DIR=$(CDPATH= cd -- "$ARCHIVE_DIR" && pwd)
TMP_LIST="$ARCHIVE_DIR/.prune-archives.$$.list"
trap 'rm -f "$TMP_LIST"' EXIT HUP INT TERM

# Only inspect direct children generated by the deploy workflow.
find "$ARCHIVE_DIR" -mindepth 1 -maxdepth 1 \( -name '.deploy-*' -o -name 'deploy-package.tar.gz' -o -name 'deploy-package.zip' \) -printf '%T@ %p\n' 2>/dev/null | sort -rn >"$TMP_LIST"
TOTAL=$(wc -l <"$TMP_LIST" | tr -d ' ')
INDEX=0
while IFS=' ' read -r _ PATHNAME; do
    [ -n "$PATHNAME" ] || continue
    INDEX=$((INDEX + 1))
    if [ "$INDEX" -le "$KEEP" ]; then
        printf '%s\n' "KEEP $PATHNAME"
    elif [ "$APPLY" -eq 1 ]; then
        case "$PATHNAME" in
            "$ARCHIVE_DIR"/.deploy-*|"$ARCHIVE_DIR"/deploy-package.tar.gz|"$ARCHIVE_DIR"/deploy-package.zip)
                rm -rf -- "$PATHNAME"
                printf '%s\n' "REMOVE $PATHNAME" ;;
            *) echo "refusing unexpected path: $PATHNAME" >&2; exit 1 ;;
        esac
    else
        printf '%s\n' "PREVIEW $PATHNAME"
    fi
done <"$TMP_LIST"

printf '%s\n' "Found $TOTAL archive entries; keeping newest $KEEP."
